name: CheckFeed
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:
jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser
          pip install tweepy
          pip install selenium
          pip install webdriver-manager
          pip install pyvirtualdisplay
      - name: Check RSS & Tweet
        env:
          API_KEY: ${{ secrets.consumer_key }}
          API_SECRET: ${{ secrets.consumer_secret }}
          ACCESS_TOKEN: ${{ secrets.access_token }}
          ACCESS_SECRET: ${{ secrets.access_token_secret }}
        uses: nick-invision/retry@v2
        with:
              timeout_minutes: 45
              max_attempts: 3        
              command: python bot.py
      - name: Upload Database
        if: always()
        run: |
          git config --global user.name 'GithubBot'
          git remote set-url origin https://x-access-token:${{ secrets.TOKEN_GITHUB }}@github.com/${{ github.repository }}
          git diff-index --quiet HEAD || git commit --allow-empty -am "Automated changes"
          git push